<?php

/**
 * Implements hook_page_attachments().
 */
function ga_disable_page_attachments(array &$page) {
  // Activate only if GA ID is set.
  $ga_id = \Drupal::config('ga_disable.settings')->get('ga_id');
  if (empty($ga_id)) {
    return;
  }

  // Add JS above all scripts.
  $page['#attached']['html_head'][] = [
    [
      '#type' => 'html_tag',
      '#weight' => -100,
      '#tag' => 'script',
      '#attributes' => [
        'src' => base_path() . drupal_get_path('module', 'ga_disable') . '/js/ga_disable.js',
        'data-id' => $ga_id,
        'id' => 'ga_disable',
      ],
    ], 'ga-disable-script',
  ];
}
